name: game_hub
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  marquee: ^2.2.3

  cupertino_icons: ^1.0.8
  loading_animation_widget: ^1.3.0
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  package_info_plus: ^8.3.0
  wakelock_plus: ^1.3.2
  fluttertoast: ^8.2.12
  sqflite: ^2.4.2
  http: ^1.4.0
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: DMSerifText
      fonts:
        - asset: assets/fonts/DMSerifText-Regular.ttf

flutter_launcher_icons:
  image_path: assets/images/joystick.png
  android: "launcher_icon"
  min_sdk_android: 21

flutter_native_splash:
  image: assets/images/joystick.png
  color: "#ffffff"


